#.travis.yml

language: node_js
node_js:
  - "8.10"

branches:
  only:
    - master

before_script:
  - npm install

script:
  - ng test
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change