#.travis.yml

language: node_js
node_js:
  - "8.10"
sudo: required
addons:
  chrome: stable
branches:
  only:
    - master

script:
  - ng lint
  - ng test
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change